### ISSUE TITLE
Content for lecture: "Annotation resources"

### ISSUE THREAD

**Issue by jotsetung** [Bioconductor/CSAMA#1]
Was already thinking about the content for the *Annotation resources* lecture for CSAMA2017.

My proposal would be:
+ First part (~ 30 minutes): @mtmorgan with a general overview (`AnnotationDbi`, `org.*`, `AnnotationHub`, `biomaRt`, ...) similar to https://github.com/Bioconductor/BiocIntro/blob/Technion-2016/vignettes/S6_Annotation_and_performance.Rmd, **Annotation** section.
+ Second part (~ 15 minutes): @jotsetung with `ensembldb`:
  - `ensembldb` intro.
  - `AnnotationFilter` intro.
  - filtering `EnsDb`s.
  - building/getting `EnsDb` packages.
  - `EnsDb` and `AnnotationDbi`.
  - protein annotations with `ensembldb`.

@mtmorgan , what do you think?

**Comment by mtmorgan** [comment]
Sounds good to me.

**Comment by jotsetung** [comment]
Referenced to the wrong issue. Second part added: https://github.com/Bioconductor/CSAMA/commit/208792fa207b15be7e3fa8c563de06701c84dab2
