### ISSUE TITLE
Content for workshop: Mass spec proteomics & metabolomics

### ISSUE THREAD

**Issue by jotsetung** [Bioconductor/CSAMA#2]
For the metabolomics part I planned to show:
+ Data import, organization and handling (read data, access spectra, extract chromatogram, simple QC).
+ Chromatographic peak detection
+ Alignment/retention time correction
+ Correspondence (grouping of chromatographic peaks across samples)
+ Exploring feature data (simple PCA, ev. diff exp etc).

So, in principle this just handles the pre-processing that can be done with `xcms` and presenting the new capabilities of `xcms` (`XCMSnExp` object extending the `OnDiskMSnExp`, `Chromatogram` class etc). For time reasons I would not go into normalization, signal drift adjustment and metabolite identification.

@lgatto , I thought of putting all that stuff into a separate `Rmd`. We might decide to fuse your and my `Rmd`, but I think the topics are too different.

@lgatto what you think of that?

**Comment by lgatto** [comment]
Looks good.

**Comment by jotsetung** [comment]
Some more organizational, @lgatto , are you planning to provide this workshop as a package, such as *ProteomicsBioc2016Workshop*?
 If yes, should we join our workshops/vignettes into one package or keep them in separate packages?
Generally I think it would be easier to keep them separate, but I would be OK fusing them.

**Comment by lgatto** [comment]
I suggest we put all our material (`Rmd`, `md` and whatever final format) in here with packages (possibly new ones) as external dependencies.

**Comment by jotsetung** [comment]
OK, so no package but single Rmd files - might indeed be easier for the participants.
