### ISSUE TITLE
Lecture: Mass spec Proteomics & Metabolomics

### ISSUE THREAD

**Issue by jotsetung** [Bioconductor/CSAMA#3]
@lgatto would it be OK for you to split the lecture into 35 and 20 minute parts (first part your proteomics, second part my metabolomics)?

**Comment by lgatto** [comment]
In principle, I'm fine with splitting the lecture, but let's set up a table of content of the different topic that should be covered to (1) make sure there is no overlap/repetition and (2) get the time splitting right. I'll start some topics in the next post, under this issue - please add your topics and amend as appropriate.

**Comment by lgatto** [comment]
- Brief intro on how MS works
- Raw MS data (linked to the *how MS works* section)
- MS quantitation: MS1 vs MS2, label-free vs labelled
- Peptide identification and protein inference
- Proteomics data processing overview
- Some packages of interest (summary of above, could be joined for proteomics/metabolomics)

**Comment by jotsetung** [comment]
had the timings wrong above, 35 + 20 is 55 mins ;) think I could reduce mine down to 15.

Title would be:
**Metabolomics data analysis with Bioconductor**
+ Short intro into metabolomics
+ Short LCMS intro
+ LCMS-based data pre-processing
   - Chromatographic peak detection
   - Sample alignment
   - Correspondence

This would describe in brief the topics of the (metabolomics part from the) afternoon workshop.

**Comment by lgatto** [comment]
It looks like *Short LCMS intro* and *Brief intro on how MS works* are overlapping. In my case, I would also introduce *MSMS*, but otherwise, I expect the content to be equivalent. My goal is to clarify how the data in an `MSnExp` related to what happens in the mass spec. 

Are you happy with me presenting this for both of us, making sure that you add any parts that are essential for the metabolomics part?

**Comment by jotsetung** [comment]
Fine for me if you include also the LCMS part. I had it only very very short (see also https://github.com/Bioconductor/CSAMA/blob/2017/lecture/4-thursday/lecture-14b-Metabolomics/Metabolomics.org) - eventually I'd then just keep the LCMS image to emphasize that in metabolomics we aim to identify *chromatographic peaks* in contrast to *mass peaks*.

**Comment by lgatto** [comment]
LC-MS is included in LC-MSMS, so yes, I fill address it. I also intend to talk about different ways to quantify MS data, including XICs. Best is probably for you to have your material at hand in case you need to clarify a few concepts, and/or amend my material once it's up.

**Comment by jotsetung** [comment]
Fine for me. I try to keep my part as simple and short as possible (I'll not add additional things/slides - if at all I will shorten it).
